
name: Build

on:
  push:
    branches: [ "master" ]
    tags:
      - '*'
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        cache: 'npm'
        
    - name: Run CI
      run: npm ci
      
    - name: Build
      run: npm run build --if-present
      
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with: 
        name: digsig
        path: digsig.zip
    
  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: digsig
          path: .

      - name: Extract tag name
        id: extract_tag
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Rename artifact
        run: mv digsig.zip digsig-${{ env.TAG }}.zip

      - name: Get the changelog
        id: changelog
        run: |
          echo "changelog=$(git log -1 --pretty=format:'%s' $GITHUB_REF)" >> $GITHUB_ENV

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG }}
          release_name: Release ${{ env.TAG }}
          draft: true
          prerelease: false
          body: ${{ env.changelog }}
          files: digsig-${{ env.TAG }}.zip