name: Create Release

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  release:
    if: github.event.workflow_run.conclusion == 'success' && startsWith(github.event.workflow_run.head_commit.message, 'Release')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download artifact from the latest successful workflow run
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: Build
          name: digsig
          path: .
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: List downloaded files for debugging
        run: ls -alh

      - name: Extract tag name
        id: extract_tag
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Rename artifact
        run: mv digsig.zip digsig-${{ env.TAG }}.zip

      - name: Get the changelog
        id: changelog
        run: |
          echo "changelog=$(git log -1 --pretty=format:'%s' $GITHUB_REF)" >> $GITHUB_ENV

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG }}
          release_name: Release ${{ env.TAG }}
          draft: true
          prerelease: false
          body: ${{ env.changelog }}
          files: digsig-${{ env.TAG }}.zip